steps:

  - id: Build & Push image
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --dockerfile=/workspace/Dockerfile
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/awbw-notifier/awbw-notifier:${_APP_VERSION}
      - --cache=true
      - --target=production

substitutions:
  _REGION: 'europe-west1'
  _APP_VERSION: $COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
